# NumPy 학습

1. 파이썬에서 배열을 사용하기 위한 수치 해석용 표준 패키지
- 적은 메모리로 데이터를 빠르게 처리할 수 있음
- 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용
- 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠름
- 벡터화 연산(vectorized operation)을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있음
- 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있음
- C언어의 배열처럼 연속적인 메모리 배치를 하기 때문에 모든 원소가 같은 자료형이어야 함
- 이러한 제약사항이 있는 대신 원소에 대한 접근과 반복문 실행이 빨라짐
- ndarray 는 N-dimensional Array의 약자로 1차원, 2차원,  3차원 배열 등의 다차원 배열 자료 구조를 지원
- **2차원 배열은 행렬(matrix)** 이라고 하는데 행렬에서는 가로줄을 행 *(row)이라고 하고 세로줄을 *열(column)이라 함
- 다차원 배열 : 리스트의 리스트(list of list)를 이용하면 2차원 배열을 생성할 수 있음. 
- 안쪽 리스트의 길이는 행렬의 열의 수 즉, 가로 크기가 되고 바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기를 의미
- url<br>
http://www.numpy.org/<br>
https://docs.scipy.org/doc/numpy-1.15.0/reference/index.html#reference


### NumPy 패키지 import

> NumPy는 np라는 이름으로 임포트하는 것이 관례

In [32]:
!pip show numpy

Name: numpy
Version: 1.15.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\playdata\anaconda3\lib\site-packages
Requires: 
Required-by: tables, seaborn, PyWavelets, pytest-doctestplus, pytest-arraydiff, patsy, pandas, odo, numexpr, numba, mkl-random, mkl-fft, matplotlib, h5py, datashape, Bottleneck, bokeh, bkcharts, astropy


In [33]:
import numpy as np

### Numpy 필요성 인지를 위한 간략 코드
- 반복문 실행 시간 비교하기

In [3]:
numpyArray = np.arange(10000000)
plist = list( range(10000000) )

In [4]:
%time for _ in range(10): numpyArray = numpyArray * 2
%time for _ in range(10): plist = [x * 2 for x in plist]

Wall time: 438 ms
Wall time: 17 s


### NumPy 모듈을 사용한 1차원 배열 만들기

- array 함수에 리스트를 넣으면 배열로 변환

In [5]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(data)
type(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [ ]:
# 정수 배열




In [ ]:
type(data)

In [8]:
#dtype을 이용한 실수 배열 타입
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype = 'float')
data

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
type(data)

### NumPy 모듈을 사용한  2차원 배열 만들기

In [10]:
data = np.array([[1,2,3], [4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 이건 몇차원인가요?   N Dimension
data.ndim

2

In [12]:
# 몇행 몇열인가요?
data.shape

(2, 3)

In [14]:
print(data)
data[0][2]

[[1 2 3]
 [4 5 6]]


3

In [16]:
data[1][2] = 60
print(data)

[[ 1  2  3]
 [ 4  5 60]]


In [17]:
# 행의 개수
len(data)

2

In [48]:
# 열 개수
len(data[1])

3

### NumPy 모듈을 사용한  3차원 배열 만들기

리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있음<br>
크기를 나타낼 때는 가장 **바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로** 표시<br>
예를 들어 2 x 3 x 4 배열은 다음과 같이 구성

In [22]:
# 두 덩어리 / 3행 (리스트 수) / 4열(원소 개수)
data = np.array([[  [1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]],
                 
                    [[13,14,15,16],
                     [17,18,19,20],
                     [21,22,23,24]]])

3차원 배열의 행, 열, 깊이

In [23]:
# 데이터 몇 차원?
data.ndim

3

In [24]:
# 몇차원 몇행 몇열??
data.shape

(2, 3, 4)

In [29]:
#
print(len(data))

#
print(len(data[0]))

2
3


In [31]:
data[1][2][3] = 47
print(data)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 47]]]


In [43]:
data[0][0][2]

3

### NumPy 함수를 사용하여 배열 생성하기

1. 규모가 큰 배열의 경우에는 NumPy에 내장된 루틴을 사용해서 처음부터 배열을 생성하는 것이 효율적
- 주요 함수<br>
a. zeros, ones <br>
b. zeros_like, ones_like<br>
c. empty<br>
d. arange : 특정한 규칙에 따라 증가하는 수열 만들기<br>
e. linspace, logspace : 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할<br>
f. rand, randn<br>

In [50]:
#0 값으로 정수를 만들어보기
data = np.zeros(10, dtype = int)

In [52]:
data.ndim

1

In [54]:
data.shape

(10,)

In [57]:
# 1값으로 10개의 데이터를 보유한 numpy 배열 만들고 출력
# data = np.ones(10)  => 생략 시 1.0 이런식의 실수로 나옴
data = np.ones(10, dtype = int)
data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [60]:
# 다차원 배열
# 2행 3열   /   dtype은 int
data = np.zeros((2, 3), dtype = int)

In [62]:
data

array([[0, 0, 0],
       [0, 0, 0]])

In [64]:
data[0][2] = 100
print(data)

[[  0   0 100]
 [  0   0   0]]


In [66]:
# 2행 3열의 data변수의 열의 값 3이 출력되게 하세요.
len(data)    # 행의 개수
len(data[0]) # 첫번째 행이 보유한 열의 개수

3

In [68]:
# 5로 채워진 3x5배열 구성하기
data = np.full((3,5), 5)
data

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [72]:
# 0~10까지 범위 내에서 2씩 증가되는 배열 만들기
data = np.arange(0, 10, 2)
data

array([0, 2, 4, 6, 8])

 ### linspace

In [78]:
# 0.1 ~ 1까지 10개의 값을 뽑는 배열
data = np.linspace(0.1, 1, 10)
data

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [75]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [76]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### np.logspace : 

In [79]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

### np.random .random : 난수 발생시키는 함수

In [80]:
np.random.random((3, 3))

array([[0.49121202, 0.58396302, 0.10856099],
       [0.03072796, 0.07924739, 0.83608873],
       [0.66553547, 0.04396806, 0.50966285]])

### np.random.randint : 정수형태의 난수 발생시키는 함수

In [90]:
np.random.randint(0,10,(3,3))

array([[5, 6, 7],
       [2, 7, 3],
       [4, 1, 3]])

- np.eye() : 단위 행렬 구성 
- [API doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)

In [ ]:
# 3x3 단위 행렬 만들기
np.eye(3)

In [174]:
x[5:8]= 30
x

array([ 0,  1,  2,  3,  4, 30, 30, 30,  8,  9])

In [175]:
y  = x[5:8]
y

array([30, 30, 30])

In [176]:
y[0] = 100
y

array([100,  30,  30])

In [177]:
x

array([  0,   1,   2,   3,   4, 100,  30,  30,   8,   9])

### .copy() 로 변수를 복사한 뒤 그걸 갖고 놀면 원본데이터에 영향을 미치지 않는다.

In [179]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
y = x[5:8].copy()
y

array([5, 6, 7])

In [181]:
y[0] = 100 
y

array([100,   6,   7])

In [182]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## NumPy 배열의 기초

### 배열 속성 지정

> 각 배열이 보유하고 있는 속성들

1. ndim : 차원의 개수
- shape : 각 차원의 크기
- size : 전체 배열 크기 (랜덤 범위의 시작점이 없으면 size를 적어줘야 한다.) 
<br><br>

2. randint(maxno, size = (n x m)) or randint(minno, maxno, (n x m))
- 정수형의 난수 발생 학습

In [91]:
# 동일한 난수 배열이 생성되도록 시드값 설정
np.random.seed(0)

정수 범위내의 난수 발생해서 1차원~3차원 배열 생성해 보기

In [92]:
x1 = np.random.randint(10, size=6) # 1차원 배열
x2 = np.random.randint(10, size=(3, 4)) # 2차원 배열
x3 = np.random.randint(10, size=(3, 4, 5))# 3차원 배열

In [136]:
x1 = np.random.randint(0, 10, 6) # 1차원 배열
x1 = np.random.randint(10, size = 6)

array([8, 4, 7, 0, 4, 9])

## 배열 indexing : 단일 요소 접근하기

In [137]:
x1 = np.random.randint(10, size = 6)

In [142]:
x1

array([0, 6, 4, 2, 4, 6])

### 배열의 색인과  슬라이싱 
> x[start : stop : step] <br>
하위 배열에 접근하기

In [145]:
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
# 3칸씩 걸러내는 구성
x[::3]

array([0, 3, 6, 9])

In [149]:
x[:10:3]

array([0, 3, 6, 9])

In [151]:
# 3 x 3 행렬

arr2d = np.array( [[1,2,3],
                  [4,5,6],
                  [7,8,9]] )

In [154]:
arr2d.shape

(3, 3)

In [155]:
# 1행, 2행만 출력하려면?
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [168]:
arr2d[:, 1:2]

array([[2],
       [5],
       [8]])

### 데이터 복사 이해하기

> NumPy는 대용량 데이터 처리를 염두해 두고 설계되었기 때문에 NumPy가 데이터 복사를 남발할 경우 성능과 메모리 문제 발생 가능성이 있음
<br>
별도의 복사된 데이터를 활용하고자 할 경우 copy() 함수 사용

copy() 함수를 사용하지 않은 경우

In [170]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

copy() 함수를 사용한 경우

In [171]:
# index 시작 : 끝
x[3:8]

array([3, 4, 5, 6, 7])

> 다차원 하위 배열

In [183]:
x2 = np.random.randint(10, size=(3,4)) # 2차원 배열

In [184]:
x2

array([[3, 3, 7, 8],
       [5, 0, 8, 5],
       [4, 7, 4, 1]])

In [195]:
'''
1. x2가 몇차원 배열인지 확인
2. x2[0]은 몇차원 배열인지 확인
3. x2의 구조(shape)
4. x2[0]의 구조
5. x2 모든 1행, 모든 4열의 데이터를 출력
6. x2의 모든 2행까지 모든 4열까지
7. x2의 모든 행의 0~2컬럼값들만 출력
'''

'\n1. x2가 몇차원 배열인지 확인\n2. x2[0]은 몇차원 배열인지 확인\n3. x2의 구조(shape)\n4. x2[0]의 구조\n5. x2 모든 1행, 모든 4열의 데이터를 출력\n6. x2의 모든 2행까지 모든 4열까지\n7. x2의 모든 행의 0~2컬럼값들만 출력\n'

In [203]:
print("문제1 : ", x2.ndim, sep='\n')
print("문제2 : ", x2[0].ndim, sep='\n')
print("문제3 : ", x2.shape, sep='\n')
print("문제4 : ", x2[0].shape, sep='\n')
print("문제5 : ", x2[:1, :5], sep='\n')
print("문제6 : ", x2[:2, :5], sep='\n')
print("문제7 : ", x2[:, :3], sep='\n')

문제1 : 
2
문제2 : 
1
문제3 : 
(3, 4)
문제4 : 
(4,)
문제5 : 
[[3 3 7 8]]
문제6 : 
[[3 3 7 8]
 [5 0 8 5]]
문제7 : 
[[3 3 7]
 [5 0 8]
 [4 7 4]]


> 배열의 재 구조화

In [208]:
x = np.arange(1,10)

In [209]:
# reshape() 메소드
.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [216]:
x = np.array([1,2,3])

In [217]:
x.ndim

1

In [218]:
x.shape

(3,)

In [219]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

> 배열 연결 및 분할
- 여러 배열을  하나로 결합 또는 하나의 배열을 여러 개의 배열로 분할하기
- np.concatenate(numpy의 배열과 python의 list 결합도 가능)
- np.vstack, np.hstack 루틴을 이용해 두 배열 결합 및 연결

In [34]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [35]:
data= np.concatenate([x,y,z])
data

NameError: name 'z' is not defined

2차원 배열간의 결합

In [52]:
data=np.array([[1,2,3],[5,6,7]])
data

array([[1, 2, 3],
       [5, 6, 7]])

In [53]:
data.ndim

2

In [54]:
data.shape

(2, 3)

In [55]:
# 2차원 배열 두가지로 새로운 numpy 배열 생성
data2=np.array([data, data])

In [56]:
data2

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [57]:
data2[0]

array([[1, 2, 3],
       [5, 6, 7]])

In [58]:
data2.shape

(2, 2, 3)

In [59]:
data

array([[1, 2, 3],
       [5, 6, 7]])

In [60]:
data2=np.concatenate([data, data], axis=1)

In [61]:
data2

array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])

In [62]:
data2.shape

(2, 6)

In [64]:
data3= np.concatenate([data, data], axis=0)
data3

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [65]:
data3.shape

(4, 3)

In [66]:
data

array([[1, 2, 3],
       [5, 6, 7]])

> 혼합된 차원의 배열
- 행의 수나 열의 수가 같은 두개 이상의 배열을 연결하여 더 큰 배열 생성하는  명령어
- np.vstack : 수직 스택, vertical stack, !컬럼 개수는 맞아야 함!<br>
- np.hstack : 수평 스택, horizontal stack, 하나의 컬럼에 속해있는 row 개수는 동일해야 함
- dstack : 제 3의 축, 즉 행이나 열이 아닌 깊이 방향으로 배열을 결합, 가장 안쪽의 원소 차원이 증가
- stack : 사용자가 지정한 차원(축)으로 연결
- r_ : hstack과 함께 배열을 좌우로 연결
- c_ : 배열의 차원을 증가시킨 후 좌우로 연결, 가령 1차원 배열을 연결하면 2차원 배열이 됨
- tile : 동일한 배열을 반복하여 연결

In [68]:
x = np.array([1,2,3])
data = np.array([[5,6,7], [8,9,10]])

In [69]:
x

array([1, 2, 3])

In [70]:
data

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [71]:
print(x.ndim, ' ', data.ndim)

1   2


In [75]:
# 배열을 수직으로 추가 하는 함수
np.vstack([x,data])

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [76]:
np.vstack([data,x])

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 1,  2,  3]])

In [77]:
x

array([1, 2, 3])

In [81]:
data

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [82]:
x.ndim

1

In [83]:
data.ndim

2

In [79]:
np.hstack([data, x])

ValueError: all the input arrays must have same number of dimensions

In [84]:
y=np.array([[100],[100]])

In [86]:
y.ndim

2

In [87]:
np.hstack([data, y])

array([[  5,   6,   7, 100],
       [  8,   9,  10, 100]])

In [88]:
data

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [89]:
x

array([1, 2, 3])

In [98]:
z = np.array([1, 2])

In [99]:
z

array([1, 2])

In [100]:
z.ndim

1

In [105]:
np.hstack([data, z]) #예외 발생 왜?

ValueError: all the input arrays must have same number of dimensions

In [106]:
np.hstack([data,[[x],[z]]])

array([[5, 6, 7, array([1, 2, 3])],
       [8, 9, 10, array([1, 2])]], dtype=object)

> 배열 분할하기
- np.split, np.hsplit, np.vsplit

In [107]:
x = [1,2,3,100,100,3,2,1]

In [120]:
x1, x2, x3 = np.split(x,[3,5])
print(x1)
print(x2)
print(x3)

[1 2 3]
[100 100]
[3 2 1]


In [ ]:
'''
1. arange(?).reshape(?)

array([[ 0, 1, 2, 3],
       [ 4, 5, 6, 7],
       [ 8, 9, 10, 11],
       [ 12, 13, 14, 15]])

2. up, down = split(?, ?)
up 출력시
[[0, 1, 2, 3]]

'''

In [123]:
data=np.array([[ 0, 1, 2, 3],
       [ 4, 5, 6, 7],
       [ 8, 9, 10, 11],
       [ 12, 13, 14, 15]])


In [125]:
up, down=np.split(data, [1])
print(up)
print(down)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [127]:
data=np.zeros((3,4), dtype=int)

In [141]:
data[0][0]=1
data[1][1]=1
data[2][2]=1

data

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [142]:
x=np.tile(data, 2)

In [143]:
x

array([[1, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0]])

> 전치 연산
- 2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업
- 이는 배열의 T 속성으로 구할 수 있음 (T:세워줌)
- 메서드가 아닌 속성 

In [144]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
data.T

array([[1, 4],
       [2, 5],
       [3, 6]])

> 다차원 배열을 1차원으로 변환하기
1. flatten or  ravel 함수 사용

In [159]:
data = np.arange(1,9,1)

In [161]:
data=data.reshape(4,2)
data

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### 벡터화 연산(vectorized operation)

1.  배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리
- 일반 for 반복문 없이 한번의 연산으로 처리 가능
- 실행 속도도 빠름
- 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [ ]:
# 일반 python 배열
data = [0, 1, 2, 3, 4, 5]

In [ ]:
# for 반복문을 사용힌 경우
result = []
for no in data:
    result.append(no*2)
result

> NumPy는 벡터화 연산 사용시 빠른 연산 가능

In [ ]:
x = np.array(data)
x

In [ ]:
x * 2

> 일반 리스트 객체에 정수를 곱하면 객체의 크기가 정수배 만큼으로 증가

In [ ]:
data = [1,2,3]
data * 2

> 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

<!--NAVIGATION-->
<[step02 NumPy 함수 학습](step02_NumpyFun.ipynb) >