# 난수 발생과 카운팅

# 시드(seed)에 대한 학습

1. 필요성 : 향후 학습 및 개발시 코드의 결과를 재현하기 위한 기술중 하나로 발생되는 난수를 예측할 수 있게 설정하는 하나의 기술
2. 원리 : 컴퓨터 프로그램에서 발생하는 무작위 수는 어떠한 특정한 시작 숫자를 제시해주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성한다. 
3. 사용: seed라는 이 값을 동일하게 맞춰서 사용하면 된다 함

In [46]:
import numpy as np

In [47]:
np.random.rand(5)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [48]:
np.random.rand(10)

array([0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194])

In [49]:
np.random.rand(5)

array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ])

In [50]:
np.random.seed(0)

In [51]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [52]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [53]:
np.random.seed(0)

In [54]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [55]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])